steps:

    - name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        docker pull gcr.io/$PROJECT_ID/ubuntu-18.04_all-dependencies:latest \
        || exit 0

    - name: 'gcr.io/cloud-builders/docker'
      args: ['build',
             '-t',
             'gcr.io/$PROJECT_ID/ubuntu-18.04_all-dependencies:latest',
             '--cache-from',
             'gcr.io/$PROJECT_ID/ubuntu-18.04_all-dependencies:latest',
             'util/dockerfiles/ubuntu-18.04_all-dependencies']

    - name: 'gcr.io/$PROJECT_ID/ubuntu-18.04_all-dependencies:latest'
      entrypoint: 'scons'
      args: ['build/NULL/unittests.opt', '-j', '4']

    - name: 'gcr.io/$PROJECT_ID/ubuntu-18.04_all-dependencies:latest'
      dir: 'tests'
      entrypoint: 'python'
      args: ['main.py', 'run', '-j', '4', '-t', '8', '--length', 'quick']

images: ['gcr.io/$PROJECT_ID/ubuntu-18.04_all-dependencies:latest']
options:
      machineType: 'N1_HIGHCPU_8'
timeout: 18000s # 5 Hours
