#!/bin/bash
#Author: Shail Dave
#Last Edited: June 20, 2017

#Expected arguments or inputs - .c or .cpp files

#Set Paths
ccf_root=""
install_path=""
obj="obj"
objFound=0;
searchstring=".o"
src="clang -w -g -O3 -mllvm -force-vector-width=1 -fno-unroll-loops -Wpadded --target=armv7a-none-linux-eabi -isystem /usr/arm-linux-gnueabi/include";
srcIR="clang -w -g -O3 -mllvm -force-vector-width=1 -Wpadded -fno-unroll-loops --target=armv7a-none-linux-eabi -isystem /usr/arm-linux-gnueabi/include -S -o - -emit-llvm";
linkModule="";
combineObj=0;
objNum=0;
MakeType=2;
LIB="";

zero=0;
target_arm=0;

#-fno-unroll-loops
#Check if file exists
if [ ! -f ./combinedIR.ll ]; then 
	clang -w -O3 --target=armv7a-none-linux-eabi -isystem /usr/arm-linux-gnueabi/include $ccf_root/scripts/CGRALib/cgra.c -S -o - -emit-llvm -o from_clang.ll
	opt -loop-simplify -redundant-dbg-inst-elim from_clang.ll -o simplified.bc
	llvm-dis -f simplified.bc -o combinedIR.ll
fi

j=1;
for i in "$@"
do
	#If switch is beginning with -o, check for object file name
	if [[ "$i" == *-o* ]]
	then
		objNum=$(( j + 1 ))
        fi
	if [[ $j -eq $objNum ]]		
	then
	    obj="${i##*/}"
	    if [[ "$obj" != *.* ]]
	    then
		objFound=1;
		MakeType=1;
		obj="$i"; 
		break;
	    else
		MakeType=2;
	    fi

	fi
	if [[ "$i" == *arm* ]]
	then
	  echo "Compiling for ARM!"
	  target_arm=1;
	fi
	((j = j + 1))
done

if [[ $objFound -gt $zero ]]
then
	MakeType=1;
	for i in "$@"
	do
		if [[ "$i" == *.o ]]
		then
			MakeType=3;
			break;
		fi
	done
else
	#TypeTwo
	for i in "$@"
	do 
    	    src+=" $i"
	    if [[ "$i" == *.o ]]
  	    then
	    	objFound=1;    
	        srcIR+=" temp.ll"
		echo "$i" >> tempObjList.txt
	    else
	        srcIR+=" $i"
	    fi	
	    if [ -f "$i" ] && [[ "$i" != *.o ]]
	    then
		tempString=`echo $i | sed -e 's/\.[^.]*$//'`
		echo "./$tempString.o" >> tempObjList.txt
            fi
	done
	#echo "cgracc.87: src = $src - srcIR = $srcIR"
	$src
	if [[ $objFound -eq $zero ]]
	then
	    srcIR+=" -o temp.ll"
	fi
	#echo here
	$srcIR

	llvm-link temp.ll combinedIR.ll -S -o combinedIR.ll
	exit
fi

objFound=0;

if [ $MakeType -eq 1 ]
then
    #TypeOne
    for i in "$@"
    do 
    	src+=" $i"
    done
    #echo "cgracc.108: src = $src"
    $src	
    for i in "$@"
    do 
	if [ $objFound -eq 1 ] && [ ! -f "$i" ]
	then
	    LIB+=" $i"
        fi

	if [[ "$i" == *-o* ]]
	then
	     objFound=1;
    	fi

	if [ $objFound -ne 1 ] && [ ! -f "$i" ]
	then
	    srcIR+=" $i"
        fi

	if [ -f "$i" ] && [[ "$i" != "$obj" ]]
	then
	    srcNew="$srcIR";
	    srcNew+=" $i"
            srcNew+=" -o temp.ll"
	    #echo "cgracc.132: srcNew = $srcNew"
	    $srcNew
      
	    llvm-link temp.ll combinedIR.ll -S -o combinedIR.ll
	fi
    done
else
    for i in "$@"
    do 

	if [ "$i" == "$obj" ] 
	then
	     objFound=1;
    	fi

	if [ -f "$i" ] && [[ "$i" != "$obj" ]] 
	then
	    if ! grep -q "$i" tempObjList.txt
	    then
	        LIB+=" $i"
      	    fi
	fi	

	if [ $objFound -eq 1 ] && [ ! -f "$i" ] && [[ "$i" != "$obj" ]]
	then
	    LIB+=" $i"
        fi
    done	
fi

if [[ $target_arm == 1 ]]; then
  $ccf_root/scripts/opt.sh combinedIR.ll ${install_path} ${ccf_root}
fi

if [[ $target_arm == 1 ]] || ([[ ! -f "CGRAGen.bc" ]] && [[ ! -d "CGRAExec" ]]); then
    echo "Accelerating loop not found! Compiling for CPU"
    llvm-dis CondDDGGen.bc -o CondDDGGen.ll
    llc -march="arm" CondDDGGen.ll
    clang -w -O3 -mllvm -force-vector-width=1 -Wpadded -static --target=armv7a-none-linux-eabi CondDDGGen.s -o $obj -lm
    rm *.s *.bc *.ll
    exit
fi


llvm-dis CGRAGen.bc -o CGRAGen.ll

if [ ! -f "CGRAGen.ll" ]; then
    echo "ERROR: CGRAGen.ll not found!"
    exit 1
fi

llvm-dis CGRAGen.bc -o CGRAGen.ll

llc -march="arm" CGRAGen.ll

#apply remaining optimizations here such as vectoirize
clang -w -O3 -mllvm -force-vector-width=1 -Wpadded -static --target=armv7a-none-linux-eabi CGRAGen.s -o $obj -lm 

#Delete temporary files
rm *.bc *.s #*.ll

# Check if CGRAExec exists.
if [ -d "CGRAExec" ]; then
	#Change directory
	cd CGRAExec

	noDir=$(ls -lR | grep ^d | wc -l)
	#echo "Total Loops Compiled for CGRA: " $noDir
	i=0;
	#For each of the loop folders, copy and execute run file to generate CGRA instructions
	for ((i=1; i<=noDir; i++));
	do
		cd L"$i"
    cp ../../CGRA_config.csv .
    awk -F "[,\"]" '{print $2 }' CGRA_config.csv > CGRA_config.txt
    #cp ../../run_command . #Debug purposes
    #chmod +x run_command   #Debug purposes
    #./run_command          #Debyg purposes
		cp $ccf_root/scripts/CGRALib/run.sh ./
        echo "start running run.sh"
		./run.sh ../../$obj ${ccf_root}
		cd ..
	done
	cd ..
fi

exit
